module.exports = {

  fashion_female_25: {
    name: 'Fashion Female 25-34',
    gender: 'female',
    age_range: '25-34',
    interests: ['fashion', 'shopping', 'beauty'],
    // Active hours: [hour_start, hour_end] pairs
    active_hours: {
      weekday: [[7,9],[12,13],[19,23]],
      weekend: [[9,12],[14,18],[20,23]],
    },
    avg_session_minutes: 25,
    search_queries: [
      'best fashion trends 2026','summer outfits ideas women',
      'affordable fashion brands online','how to style jeans',
      'best online clothing stores usa','zara new collection 2026',
      'nordstrom sale dresses','fashion nova reviews',
      'how to build a capsule wardrobe','what to wear to a job interview women',
      'skincare routine for dry skin','best drugstore makeup 2026',
      'ulta beauty sale','sephora favorites kit',
      'how to do a french manicure at home','best moisturizer for oily skin',
      'spring fashion trends 2026','affordable luxury bags',
      'how to dress business casual women','best white sneakers women',
    ],
    youtube_searches: [
      'get ready with me 2026','thrift flip outfit ideas',
      'haul video fashion nova','summer lookbook 2026',
      'makeup tutorial natural look','skincare routine morning',
      'how to style oversized blazer','outfit of the day',
    ],
    news_topics: ['fashion week','celebrity style','beauty trends','lifestyle'],
    visit_sites: [
      'https://www.vogue.com','https://www.elle.com',
      'https://www.nordstrom.com','https://www.zara.com/us',
      'https://www.sephora.com','https://www.refinery29.com',
      'https://www.whowhatwear.com',
    ],
    reddit_subs: ['r/femalefashionadvice','r/makeupaddiction','r/skincareaddiction'],
    consistency: {
      primary: ['fashion','beauty','shopping','lifestyle','skincare'],
      secondary: ['food','travel','fitness','home decor'],
      forbidden: ['crypto','coding','sports car','gaming'],
    },
  },

  finance_male_35: {
    name: 'Finance Male 35-44',
    gender: 'male',
    age_range: '35-44',
    interests: ['finance','investing','real estate'],
    active_hours: {
      weekday: [[6,8],[11,13],[17,20]],
      weekend: [[8,11],[15,18]],
    },
    avg_session_minutes: 18,
    search_queries: [
      'best index funds 2026','how to invest in s&p 500',
      'roth ira contribution limits 2026','401k vs roth ira',
      'best high yield savings account usa','real estate investing for beginners',
      'how to buy rental property','stock market news today',
      'bitcoin price prediction 2026','best financial advisor near me',
      'how to reduce taxes legally','passive income ideas 2026',
      'personal finance tips','mortgage rates 2026',
      'best credit cards for cash back','dividend investing strategy',
      'how to retire early fire movement','vanguard vs fidelity',
      'emergency fund how much','term life insurance vs whole life',
    ],
    youtube_searches: [
      'how to invest for beginners','passive income ideas 2026',
      'stock market explained','real estate investing tips',
      'personal finance advice','retire early fire movement',
      'index fund investing explained',
    ],
    news_topics: ['stock market','federal reserve','interest rates','economy','real estate'],
    visit_sites: [
      'https://www.investopedia.com','https://finance.yahoo.com',
      'https://www.marketwatch.com','https://www.bloomberg.com',
      'https://www.fool.com','https://www.cnbc.com',
      'https://www.wsj.com',
    ],
    reddit_subs: ['r/personalfinance','r/financialindependence','r/investing','r/realestateinvesting'],
    consistency: {
      primary: ['finance','investing','real estate','economy','retirement'],
      secondary: ['technology','news','sports','career'],
      forbidden: ['fashion','beauty','gaming','anime'],
    },
  },

  tech_male_28: {
    name: 'Tech Male 25-34',
    gender: 'male',
    age_range: '25-34',
    interests: ['technology','gadgets','software'],
    active_hours: {
      weekday: [[8,10],[13,14],[20,24]],
      weekend: [[10,14],[20,24]],
    },
    avg_session_minutes: 35,
    search_queries: [
      'best laptop 2026','iphone 17 review',
      'best programming languages to learn','react vs vue 2026',
      'best mechanical keyboard','nvidia rtx 5090 specs',
      'best monitor for programming','aws vs azure comparison',
      'how to learn python fast','best vpn service 2026',
      'cybersecurity career path','best ai tools for developers',
      'github copilot review','best ergonomic chair',
      'standing desk benefits','linux vs windows for development',
      'best headphones for work','home lab setup guide',
      'docker tutorial beginners','kubernetes explained',
    ],
    youtube_searches: [
      'best tech setup 2026','unboxing latest macbook',
      'programming tutorial python','tech review linus tech tips',
      'best coding practices','system design interview',
      'rust programming language','neovim vs vscode',
    ],
    news_topics: ['technology','artificial intelligence','startups','apple','google','microsoft'],
    visit_sites: [
      'https://www.theverge.com','https://techcrunch.com',
      'https://www.wired.com','https://stackoverflow.com',
      'https://news.ycombinator.com','https://www.arstechnica.com',
      'https://dev.to',
    ],
    reddit_subs: ['r/technology','r/programming','r/MachineLearning','r/homelab','r/pcmasterrace'],
    consistency: {
      primary: ['technology','programming','gadgets','ai','software'],
      secondary: ['gaming','science','finance','productivity'],
      forbidden: ['fashion','beauty','celebrity gossip'],
    },
  },

  health_female_40: {
    name: 'Health Female 35-44',
    gender: 'female',
    age_range: '35-44',
    interests: ['health','fitness','wellness','nutrition'],
    active_hours: {
      weekday: [[5,7],[12,13],[19,22]],
      weekend: [[7,10],[14,17]],
    },
    avg_session_minutes: 22,
    search_queries: [
      'best workout routine for women over 35','how to lose weight after 40',
      'intermittent fasting results','best protein powder for women',
      'yoga for beginners at home','healthy meal prep ideas',
      'best supplements for energy','how to sleep better',
      'mindfulness meditation benefits','best running shoes women 2026',
      'how to reduce cortisol naturally','anti-aging skincare routine',
      'perimenopause symptoms and remedies','best diet plan for weight loss',
      'gym workout plan for beginners','pilates vs yoga which is better',
      'how to build muscle women','gut health foods',
      'best collagen supplements','walking 10000 steps benefits',
    ],
    youtube_searches: [
      'home workout no equipment','healthy meal prep sunday',
      'yoga for stress relief','weight loss journey women over 40',
      'clean eating recipes','pilates beginner workout',
      'mindfulness meditation guided',
    ],
    news_topics: ['health','wellness','nutrition','fitness trends','womens health'],
    visit_sites: [
      'https://www.healthline.com','https://www.webmd.com',
      'https://www.self.com','https://www.shape.com',
      'https://www.mindbodygreen.com','https://www.eatingwell.com',
    ],
    reddit_subs: ['r/xxfitness','r/loseit','r/EatCheapAndHealthy','r/meditation'],
    consistency: {
      primary: ['health','fitness','wellness','nutrition','mindfulness'],
      secondary: ['fashion','travel','family','cooking'],
      forbidden: ['crypto','gaming','heavy metal music'],
    },
  },

  travel_female_30: {
    name: 'Travel Female 25-34',
    gender: 'female',
    age_range: '25-34',
    interests: ['travel','adventure','food','culture'],
    active_hours: {
      weekday: [[7,9],[12,13],[20,23]],
      weekend: [[9,13],[15,22]],
    },
    avg_session_minutes: 30,
    search_queries: [
      'best places to visit usa 2026','cheap flights to europe',
      'travel tips for solo women','best travel credit card',
      'airbnb vs hotel which is better','best travel insurance 2026',
      'packing list for europe trip','things to do in new york',
      'best restaurants in miami','digital nomad visa countries',
      'how to travel on a budget','best travel backpack women',
      'hidden gems usa road trip','best beach destinations usa',
      'japan travel guide 2026','bali travel tips',
      'best credit card travel rewards','travel photography tips',
      'road trip across america','best hostels europe',
    ],
    youtube_searches: [
      'travel vlog europe 2026','solo travel tips women',
      'budget travel hacks','best travel destinations 2026',
      'travel packing tips','japan travel guide',
      'digital nomad life vlog',
    ],
    news_topics: ['travel','tourism','airlines','hotels','destination guides'],
    visit_sites: [
      'https://www.tripadvisor.com','https://www.lonelyplanet.com',
      'https://www.travelandleisure.com','https://www.cntraveler.com',
      'https://www.booking.com','https://www.nomadicmatt.com',
    ],
    reddit_subs: ['r/solotravel','r/travel','r/digitalnomad','r/shoestring'],
    consistency: {
      primary: ['travel','adventure','food','culture','photography'],
      secondary: ['fashion','fitness','language learning'],
      forbidden: ['heavy finance','coding','sports statistics'],
    },
  },

};
